package emoji

// emojiData returns the built-in curated emoji set. Shortcodes follow the
// common GitHub/Slack-style names so muscle memory carries over.
func emojiData() []Emoji {
	return []Emoji{
		// Smileys & emotion
		{"😀", "grinning", []string{"smile", "happy", "face"}, "smileys"},
		{"😃", "smiley", []string{"happy", "joy", "haha"}, "smileys"},
		{"😄", "smile", []string{"happy", "joy", "laugh"}, "smileys"},
		{"😁", "grin", []string{"happy", "smile"}, "smileys"},
		{"😆", "laughing", []string{"happy", "haha", "lol"}, "smileys"},
		{"😅", "sweat_smile", []string{"hot", "relief", "phew"}, "smileys"},
		{"🤣", "rofl", []string{"lol", "rolling", "laugh"}, "smileys"},
		{"😂", "joy", []string{"tears", "laugh", "cry", "lol"}, "smileys"},
		{"🙂", "slightly_smiling_face", []string{"smile"}, "smileys"},
		{"🙃", "upside_down_face", []string{"silly", "sarcasm"}, "smileys"},
		{"😉", "wink", []string{"flirt"}, "smileys"},
		{"😊", "blush", []string{"happy", "smile", "shy"}, "smileys"},
		{"😇", "innocent", []string{"angel", "halo"}, "smileys"},
		{"🥰", "smiling_face_with_three_hearts", []string{"love", "adore"}, "smileys"},
		{"😍", "heart_eyes", []string{"love", "crush"}, "smileys"},
		{"🤩", "star_struck", []string{"wow", "amazed", "eyes"}, "smileys"},
		{"😘", "kissing_heart", []string{"kiss", "love"}, "smileys"},
		{"😋", "yum", []string{"tongue", "delicious", "tasty"}, "smileys"},
		{"😛", "stuck_out_tongue", []string{"tongue", "silly"}, "smileys"},
		{"😜", "stuck_out_tongue_winking_eye", []string{"tongue", "wink", "silly"}, "smileys"},
		{"🤪", "zany_face", []string{"crazy", "goofy"}, "smileys"},
		{"🤨", "raised_eyebrow", []string{"skeptical", "suspicious"}, "smileys"},
		{"🧐", "monocle", []string{"thinking", "inspect"}, "smileys"},
		{"🤓", "nerd", []string{"glasses", "geek"}, "smileys"},
		{"😎", "sunglasses", []string{"cool", "shades"}, "smileys"},
		{"🥳", "partying_face", []string{"party", "celebrate", "birthday"}, "smileys"},
		{"😏", "smirk", []string{"smug"}, "smileys"},
		{"😒", "unamused", []string{"meh", "annoyed"}, "smileys"},
		{"😞", "disappointed", []string{"sad"}, "smileys"},
		{"😔", "pensive", []string{"sad", "thoughtful"}, "smileys"},
		{"😟", "worried", []string{"concern", "anxious"}, "smileys"},
		{"🙁", "slightly_frowning_face", []string{"sad", "frown"}, "smileys"},
		{"😣", "persevere", []string{"struggle"}, "smileys"},
		{"😖", "confounded", []string{"frustrated"}, "smileys"},
		{"😫", "tired_face", []string{"exhausted"}, "smileys"},
		{"😩", "weary", []string{"tired", "ugh"}, "smileys"},
		{"🥺", "pleading_face", []string{"puppy", "beg", "cute"}, "smileys"},
		{"😢", "cry", []string{"sad", "tear"}, "smileys"},
		{"😭", "sob", []string{"cry", "tears", "sad"}, "smileys"},
		{"😤", "triumph", []string{"angry", "steam", "huff"}, "smileys"},
		{"😠", "angry", []string{"mad"}, "smileys"},
		{"😡", "rage", []string{"angry", "mad", "furious"}, "smileys"},
		{"🤬", "cursing", []string{"swear", "angry"}, "smileys"},
		{"🤯", "exploding_head", []string{"mind blown", "wow"}, "smileys"},
		{"😳", "flushed", []string{"embarrassed", "shy"}, "smileys"},
		{"🥵", "hot_face", []string{"heat", "sweat"}, "smileys"},
		{"🥶", "cold_face", []string{"freezing", "frozen"}, "smileys"},
		{"😱", "scream", []string{"fear", "shock", "omg"}, "smileys"},
		{"😨", "fearful", []string{"scared", "afraid"}, "smileys"},
		{"😰", "cold_sweat", []string{"nervous", "anxious"}, "smileys"},
		{"😥", "disappointed_relieved", []string{"phew", "sad"}, "smileys"},
		{"😓", "sweat", []string{"nervous"}, "smileys"},
		{"🤗", "hugs", []string{"hug", "embrace"}, "smileys"},
		{"🤔", "thinking", []string{"hmm", "consider"}, "smileys"},
		{"🤭", "hand_over_mouth", []string{"oops", "giggle"}, "smileys"},
		{"🤫", "shushing", []string{"quiet", "shh", "secret"}, "smileys"},
		{"🤥", "lying", []string{"pinocchio", "liar"}, "smileys"},
		{"😶", "no_mouth", []string{"speechless", "blank"}, "smileys"},
		{"😐", "neutral_face", []string{"meh", "blank"}, "smileys"},
		{"😑", "expressionless", []string{"blank", "meh"}, "smileys"},
		{"😬", "grimacing", []string{"awkward", "eek"}, "smileys"},
		{"🙄", "roll_eyes", []string{"eyeroll", "whatever"}, "smileys"},
		{"😯", "hushed", []string{"surprised", "woah"}, "smileys"},
		{"😴", "sleeping", []string{"zzz", "tired", "sleep"}, "smileys"},
		{"🤤", "drooling_face", []string{"drool", "hungry"}, "smileys"},
		{"😪", "sleepy", []string{"tired"}, "smileys"},
		{"😵", "dizzy_face", []string{"woozy", "ko"}, "smileys"},
		{"🤐", "zipper_mouth", []string{"quiet", "secret"}, "smileys"},
		{"🥴", "woozy_face", []string{"drunk", "dizzy"}, "smileys"},
		{"🤢", "nauseated_face", []string{"sick", "gross"}, "smileys"},
		{"🤮", "vomiting", []string{"sick", "puke", "gross"}, "smileys"},
		{"🤧", "sneezing_face", []string{"sick", "sneeze"}, "smileys"},
		{"😷", "mask", []string{"sick", "ill", "covid"}, "smileys"},
		{"🤒", "thermometer_face", []string{"sick", "fever"}, "smileys"},
		{"🤕", "head_bandage", []string{"hurt", "injured"}, "smileys"},
		{"🤑", "money_mouth", []string{"rich", "dollar"}, "smileys"},
		{"🤠", "cowboy", []string{"hat", "yeehaw"}, "smileys"},
		{"😈", "smiling_imp", []string{"devil", "evil"}, "smileys"},
		{"👿", "imp", []string{"devil", "angry"}, "smileys"},
		{"👻", "ghost", []string{"halloween", "boo", "spooky"}, "smileys"},
		{"💀", "skull", []string{"dead", "death"}, "smileys"},
		{"☠️", "skull_and_crossbones", []string{"danger", "poison"}, "smileys"},
		{"👽", "alien", []string{"ufo", "space"}, "smileys"},
		{"🤖", "robot", []string{"bot", "ai"}, "smileys"},
		{"💩", "poop", []string{"poo", "shit", "crap"}, "smileys"},
		{"🤡", "clown", []string{"joker"}, "smileys"},
		{"👋", "wave", []string{"hello", "hi", "bye", "hand"}, "people"},

		// Gestures & body
		{"👍", "thumbsup", []string{"+1", "yes", "approve", "like"}, "people"},
		{"👎", "thumbsdown", []string{"-1", "no", "dislike"}, "people"},
		{"👌", "ok_hand", []string{"okay", "perfect"}, "people"},
		{"✌️", "v", []string{"peace", "victory"}, "people"},
		{"🤞", "crossed_fingers", []string{"luck", "hope"}, "people"},
		{"🤟", "love_you_gesture", []string{"rock"}, "people"},
		{"🤘", "metal", []string{"rock", "horns"}, "people"},
		{"🤙", "call_me_hand", []string{"shaka", "hang loose"}, "people"},
		{"👈", "point_left", []string{"finger"}, "people"},
		{"👉", "point_right", []string{"finger"}, "people"},
		{"👆", "point_up_2", []string{"finger", "up"}, "people"},
		{"👇", "point_down", []string{"finger", "down"}, "people"},
		{"☝️", "point_up", []string{"finger", "one"}, "people"},
		{"✋", "raised_hand", []string{"stop", "high five"}, "people"},
		{"🤚", "raised_back_of_hand", []string{"stop"}, "people"},
		{"🖐️", "hand_splayed", []string{"five", "palm"}, "people"},
		{"🖖", "vulcan_salute", []string{"spock", "star trek"}, "people"},
		{"👏", "clap", []string{"applause", "bravo"}, "people"},
		{"🙌", "raised_hands", []string{"hooray", "celebrate", "praise"}, "people"},
		{"🤲", "open_hands_palms_up", []string{"pray", "beg"}, "people"},
		{"🙏", "pray", []string{"please", "thanks", "thank you", "hope"}, "people"},
		{"🤝", "handshake", []string{"deal", "agreement"}, "people"},
		{"💪", "muscle", []string{"strong", "flex", "gym"}, "people"},
		{"✊", "fist", []string{"power", "resist"}, "people"},
		{"👊", "punch", []string{"fist bump", "bro"}, "people"},
		{"🤛", "left_facing_fist", []string{"fist bump"}, "people"},
		{"🤜", "right_facing_fist", []string{"fist bump"}, "people"},
		{"✍️", "writing_hand", []string{"write", "sign"}, "people"},
		{"🤳", "selfie", []string{"camera", "photo"}, "people"},
		{"💅", "nail_care", []string{"manicure", "polish"}, "people"},
		{"👀", "eyes", []string{"look", "watch", "see"}, "people"},
		{"🧠", "brain", []string{"smart", "mind"}, "people"},
		{"👶", "baby", []string{"infant", "child"}, "people"},
		{"🧑", "person", []string{"adult"}, "people"},
		{"👨", "man", []string{"male", "guy"}, "people"},
		{"👩", "woman", []string{"female", "lady"}, "people"},
		{"🧓", "older_person", []string{"elderly"}, "people"},

		// Hearts & symbols
		{"❤️", "heart", []string{"love", "red"}, "symbols"},
		{"🧡", "orange_heart", []string{"love"}, "symbols"},
		{"💛", "yellow_heart", []string{"love"}, "symbols"},
		{"💚", "green_heart", []string{"love"}, "symbols"},
		{"💙", "blue_heart", []string{"love"}, "symbols"},
		{"💜", "purple_heart", []string{"love"}, "symbols"},
		{"🖤", "black_heart", []string{"love", "dark"}, "symbols"},
		{"🤍", "white_heart", []string{"love"}, "symbols"},
		{"🤎", "brown_heart", []string{"love"}, "symbols"},
		{"💔", "broken_heart", []string{"heartbreak", "sad"}, "symbols"},
		{"❣️", "heart_exclamation", []string{"love"}, "symbols"},
		{"💕", "two_hearts", []string{"love"}, "symbols"},
		{"💞", "revolving_hearts", []string{"love"}, "symbols"},
		{"💓", "heartbeat", []string{"love", "pulse"}, "symbols"},
		{"💗", "heartpulse", []string{"love", "growing"}, "symbols"},
		{"💖", "sparkling_heart", []string{"love"}, "symbols"},
		{"💘", "cupid", []string{"love", "arrow"}, "symbols"},
		{"💝", "gift_heart", []string{"love", "present"}, "symbols"},
		{"💯", "100", []string{"hundred", "perfect", "score"}, "symbols"},
		{"💢", "anger", []string{"mad", "comic"}, "symbols"},
		{"💥", "boom", []string{"explosion", "collision"}, "symbols"},
		{"💫", "dizzy", []string{"star", "sparkle"}, "symbols"},
		{"💦", "sweat_drops", []string{"water", "splash"}, "symbols"},
		{"💨", "dash", []string{"wind", "fast", "fart"}, "symbols"},
		{"🕳️", "hole", []string{"empty"}, "symbols"},
		{"💬", "speech_balloon", []string{"comment", "talk", "chat"}, "symbols"},
		{"💭", "thought_balloon", []string{"thinking", "dream"}, "symbols"},
		{"🔥", "fire", []string{"lit", "hot", "flame"}, "symbols"},
		{"⭐", "star", []string{"favorite", "rating"}, "symbols"},
		{"🌟", "star2", []string{"glowing", "shine"}, "symbols"},
		{"✨", "sparkles", []string{"shiny", "magic", "clean"}, "symbols"},
		{"⚡", "zap", []string{"lightning", "fast", "power"}, "symbols"},
		{"☀️", "sunny", []string{"sun", "weather", "clear"}, "nature"},
		{"🌈", "rainbow", []string{"pride", "weather"}, "nature"},
		{"☁️", "cloud", []string{"weather"}, "nature"},
		{"🌧️", "cloud_rain", []string{"weather", "rainy"}, "nature"},
		{"❄️", "snowflake", []string{"cold", "winter", "snow"}, "nature"},
		{"⛄", "snowman", []string{"winter", "snow"}, "nature"},
		{"🌊", "ocean", []string{"wave", "water", "sea"}, "nature"},
		{"🌙", "crescent_moon", []string{"night", "moon"}, "nature"},
		{"🌍", "earth_africa", []string{"world", "globe", "planet"}, "nature"},

		// Nature & animals
		{"🌸", "cherry_blossom", []string{"flower", "spring"}, "nature"},
		{"🌹", "rose", []string{"flower", "love"}, "nature"},
		{"🌻", "sunflower", []string{"flower"}, "nature"},
		{"🌲", "evergreen_tree", []string{"tree", "forest"}, "nature"},
		{"🌴", "palm_tree", []string{"tree", "beach", "tropical"}, "nature"},
		{"🌵", "cactus", []string{"desert", "plant"}, "nature"},
		{"🍀", "four_leaf_clover", []string{"luck", "lucky"}, "nature"},
		{"🐶", "dog", []string{"puppy", "pet"}, "nature"},
		{"🐱", "cat", []string{"kitten", "pet"}, "nature"},
		{"🦊", "fox", []string{"animal"}, "nature"},
		{"🐻", "bear", []string{"animal"}, "nature"},
		{"🐼", "panda", []string{"animal"}, "nature"},
		{"🐨", "koala", []string{"animal"}, "nature"},
		{"🦁", "lion", []string{"animal"}, "nature"},
		{"🐯", "tiger", []string{"animal"}, "nature"},
		{"🐮", "cow", []string{"animal", "moo"}, "nature"},
		{"🐷", "pig", []string{"animal", "oink"}, "nature"},
		{"🐵", "monkey_face", []string{"animal", "ape"}, "nature"},
		{"🐔", "chicken", []string{"animal", "hen"}, "nature"},
		{"🐧", "penguin", []string{"animal"}, "nature"},
		{"🐦", "bird", []string{"animal"}, "nature"},
		{"🦄", "unicorn", []string{"magic", "fantasy"}, "nature"},
		{"🐝", "bee", []string{"honey", "insect"}, "nature"},
		{"🦋", "butterfly", []string{"insect"}, "nature"},
		{"🐢", "turtle", []string{"slow", "tortoise"}, "nature"},
		{"🐍", "snake", []string{"python", "serpent"}, "nature"},
		{"🐙", "octopus", []string{"sea"}, "nature"},
		{"🐳", "whale", []string{"sea", "ocean"}, "nature"},
		{"🐬", "dolphin", []string{"sea"}, "nature"},
		{"🐟", "fish", []string{"sea"}, "nature"},

		// Food & drink
		{"🍎", "apple", []string{"fruit", "red"}, "food"},
		{"🍌", "banana", []string{"fruit"}, "food"},
		{"🍓", "strawberry", []string{"fruit"}, "food"},
		{"🍒", "cherries", []string{"fruit"}, "food"},
		{"🍑", "peach", []string{"fruit", "butt"}, "food"},
		{"🍉", "watermelon", []string{"fruit", "summer"}, "food"},
		{"🍍", "pineapple", []string{"fruit"}, "food"},
		{"🥑", "avocado", []string{"fruit", "guac"}, "food"},
		{"🍕", "pizza", []string{"food", "slice"}, "food"},
		{"🍔", "hamburger", []string{"burger", "food"}, "food"},
		{"🍟", "fries", []string{"chips", "food"}, "food"},
		{"🌮", "taco", []string{"mexican", "food"}, "food"},
		{"🌯", "burrito", []string{"mexican", "food"}, "food"},
		{"🍣", "sushi", []string{"japanese", "food"}, "food"},
		{"🍜", "ramen", []string{"noodles", "soup"}, "food"},
		{"🍰", "cake", []string{"dessert", "birthday"}, "food"},
		{"🎂", "birthday", []string{"cake", "party"}, "food"},
		{"🍪", "cookie", []string{"dessert", "biscuit"}, "food"},
		{"🍩", "doughnut", []string{"donut", "dessert"}, "food"},
		{"🍫", "chocolate_bar", []string{"candy", "sweet"}, "food"},
		{"🍬", "candy", []string{"sweet"}, "food"},
		{"🍦", "icecream", []string{"dessert", "soft serve"}, "food"},
		{"☕", "coffee", []string{"tea", "drink", "hot"}, "food"},
		{"🍵", "tea", []string{"drink", "green"}, "food"},
		{"🍺", "beer", []string{"drink", "alcohol"}, "food"},
		{"🍻", "beers", []string{"cheers", "drink"}, "food"},
		{"🍷", "wine_glass", []string{"drink", "alcohol"}, "food"},
		{"🍸", "cocktail", []string{"drink", "martini"}, "food"},
		{"🥂", "champagne_glasses", []string{"cheers", "celebrate"}, "food"},
		{"🍾", "champagne", []string{"celebrate", "party"}, "food"},

		// Activities & objects
		{"⚽", "soccer", []string{"football", "sport"}, "activities"},
		{"🏀", "basketball", []string{"sport"}, "activities"},
		{"🏈", "football", []string{"sport", "nfl"}, "activities"},
		{"⚾", "baseball", []string{"sport"}, "activities"},
		{"🎾", "tennis", []string{"sport"}, "activities"},
		{"🏐", "volleyball", []string{"sport"}, "activities"},
		{"🎮", "video_game", []string{"gaming", "controller"}, "activities"},
		{"🎲", "game_die", []string{"dice", "random"}, "activities"},
		{"🎯", "dart", []string{"target", "bullseye", "goal"}, "activities"},
		{"🎸", "guitar", []string{"music", "rock"}, "activities"},
		{"🎹", "musical_keyboard", []string{"piano", "music"}, "activities"},
		{"🎺", "trumpet", []string{"music"}, "activities"},
		{"🎤", "microphone", []string{"sing", "music", "karaoke"}, "activities"},
		{"🎧", "headphones", []string{"music", "audio"}, "activities"},
		{"🎵", "musical_note", []string{"music"}, "activities"},
		{"🎶", "notes", []string{"music"}, "activities"},
		{"🎉", "tada", []string{"party", "celebrate", "hooray"}, "activities"},
		{"🎊", "confetti_ball", []string{"party", "celebrate"}, "activities"},
		{"🎈", "balloon", []string{"party", "birthday"}, "activities"},
		{"🎁", "gift", []string{"present", "birthday"}, "activities"},
		{"🏆", "trophy", []string{"win", "award", "champion"}, "activities"},
		{"🥇", "first_place", []string{"gold", "medal", "win"}, "activities"},
		{"🎬", "clapper", []string{"movie", "film", "action"}, "activities"},
		{"📷", "camera", []string{"photo", "picture"}, "objects"},
		{"💡", "bulb", []string{"idea", "light"}, "objects"},
		{"🔦", "flashlight", []string{"torch", "light"}, "objects"},
		{"💻", "computer", []string{"laptop", "pc"}, "objects"},
		{"🖥️", "desktop", []string{"computer", "monitor"}, "objects"},
		{"⌨️", "keyboard", []string{"type"}, "objects"},
		{"📱", "iphone", []string{"phone", "mobile"}, "objects"},
		{"☎️", "phone", []string{"call", "telephone"}, "objects"},
		{"🔋", "battery", []string{"power", "charge"}, "objects"},
		{"🔌", "electric_plug", []string{"power"}, "objects"},
		{"💾", "floppy_disk", []string{"save", "disk"}, "objects"},
		{"💿", "cd", []string{"disc"}, "objects"},
		{"📀", "dvd", []string{"disc"}, "objects"},
		{"📦", "package", []string{"box", "ship", "delivery"}, "objects"},
		{"📫", "mailbox", []string{"mail", "post"}, "objects"},
		{"✉️", "envelope", []string{"mail", "email", "letter"}, "objects"},
		{"📧", "email", []string{"mail", "message"}, "objects"},
		{"🔒", "lock", []string{"secure", "private", "locked"}, "objects"},
		{"🔓", "unlock", []string{"open", "unlocked"}, "objects"},
		{"🔑", "key", []string{"password", "access"}, "objects"},
		{"🔍", "mag", []string{"search", "find", "zoom"}, "objects"},
		{"🔎", "mag_right", []string{"search", "find"}, "objects"},
		{"💰", "moneybag", []string{"money", "cash", "rich"}, "objects"},
		{"💵", "dollar", []string{"money", "cash"}, "objects"},
		{"💳", "credit_card", []string{"payment", "money"}, "objects"},
		{"📈", "chart_increasing", []string{"graph", "up", "growth", "stocks"}, "objects"},
		{"📉", "chart_decreasing", []string{"graph", "down", "loss"}, "objects"},
		{"📊", "bar_chart", []string{"graph", "stats", "data"}, "objects"},
		{"📌", "pushpin", []string{"pin", "location"}, "objects"},
		{"📎", "paperclip", []string{"attach"}, "objects"},
		{"✂️", "scissors", []string{"cut"}, "objects"},
		{"📝", "memo", []string{"note", "write", "pencil"}, "objects"},
		{"📖", "book", []string{"read", "open"}, "objects"},
		{"📚", "books", []string{"read", "library", "study"}, "objects"},
		{"🔖", "bookmark", []string{"save", "tag"}, "objects"},
		{"🗓️", "calendar", []string{"date", "schedule"}, "objects"},
		{"⏰", "alarm_clock", []string{"time", "wake"}, "objects"},
		{"⏳", "hourglass_flowing_sand", []string{"time", "wait", "loading"}, "objects"},
		{"🔔", "bell", []string{"notification", "alert"}, "objects"},
		{"🔕", "no_bell", []string{"mute", "silent"}, "objects"},
		{"🛠️", "tools", []string{"build", "fix", "wrench"}, "objects"},
		{"🔧", "wrench", []string{"fix", "tool", "settings"}, "objects"},
		{"🔨", "hammer", []string{"build", "tool"}, "objects"},
		{"⚙️", "gear", []string{"settings", "cog", "config"}, "objects"},
		{"🧰", "toolbox", []string{"tools", "repair"}, "objects"},
		{"🧪", "test_tube", []string{"science", "experiment", "lab"}, "objects"},
		{"💉", "syringe", []string{"shot", "vaccine", "medicine"}, "objects"},
		{"💊", "pill", []string{"medicine", "drug"}, "objects"},
		{"🚀", "rocket", []string{"launch", "ship", "fast", "space"}, "travel"},
		{"✈️", "airplane", []string{"flight", "travel", "fly"}, "travel"},
		{"🚗", "car", []string{"drive", "auto"}, "travel"},
		{"🚕", "taxi", []string{"cab"}, "travel"},
		{"🚲", "bike", []string{"bicycle", "cycle"}, "travel"},
		{"🏠", "house", []string{"home"}, "travel"},
		{"🏢", "office", []string{"building", "work"}, "travel"},
		{"🗺️", "world_map", []string{"travel", "map"}, "travel"},
		{"📍", "round_pushpin", []string{"location", "pin", "map"}, "travel"},

		// Flags & misc symbols
		{"🚩", "triangular_flag_on_post", []string{"flag", "warning", "red"}, "symbols"},
		{"🏁", "checkered_flag", []string{"race", "finish", "start"}, "symbols"},
		{"✅", "white_check_mark", []string{"check", "done", "yes", "ok"}, "symbols"},
		{"☑️", "ballot_box_with_check", []string{"check", "done"}, "symbols"},
		{"✔️", "heavy_check_mark", []string{"check", "done", "tick"}, "symbols"},
		{"❌", "x", []string{"cross", "no", "wrong", "delete"}, "symbols"},
		{"❎", "negative_squared_cross_mark", []string{"no", "cross"}, "symbols"},
		{"⚠️", "warning", []string{"caution", "alert", "danger"}, "symbols"},
		{"🚫", "no_entry_sign", []string{"forbidden", "ban", "stop"}, "symbols"},
		{"❓", "question", []string{"help", "what"}, "symbols"},
		{"❗", "exclamation", []string{"warning", "important"}, "symbols"},
		{"💲", "heavy_dollar_sign", []string{"money"}, "symbols"},
		{"➕", "heavy_plus_sign", []string{"add", "plus"}, "symbols"},
		{"➖", "heavy_minus_sign", []string{"subtract", "minus"}, "symbols"},
		{"➗", "heavy_division_sign", []string{"divide"}, "symbols"},
		{"♻️", "recycle", []string{"reuse", "green", "environment"}, "symbols"},
		{"🔄", "arrows_counterclockwise", []string{"refresh", "reload", "sync"}, "symbols"},
		{"🔁", "repeat", []string{"loop"}, "symbols"},
		{"▶️", "arrow_forward", []string{"play"}, "symbols"},
		{"⏸️", "pause_button", []string{"pause"}, "symbols"},
		{"⏹️", "stop_button", []string{"stop"}, "symbols"},
		{"⏭️", "next_track_button", []string{"skip", "next"}, "symbols"},
		{"🔼", "arrow_up_small", []string{"up"}, "symbols"},
		{"🔽", "arrow_down_small", []string{"down"}, "symbols"},
		{"➡️", "arrow_right", []string{"right", "next"}, "symbols"},
		{"⬅️", "arrow_left", []string{"left", "back"}, "symbols"},
		{"⬆️", "arrow_up", []string{"up"}, "symbols"},
		{"⬇️", "arrow_down", []string{"down"}, "symbols"},
		{"🆗", "ok", []string{"okay", "approve"}, "symbols"},
		{"🆕", "new", []string{"fresh"}, "symbols"},
		{"🆒", "cool", []string{"awesome"}, "symbols"},
		{"🔝", "top", []string{"up", "best"}, "symbols"},
		{"💤", "zzz", []string{"sleep", "tired"}, "symbols"},
	}
}
